#############################################################
## NOT FOR PRODUCTION USE.                                 ##
## THE CONTENT OF THIS FILE IS FOR LEARNING PURPOSES ONLY  ##
## created by David Surey, Amazon Web Services, 2020       ##
#############################################################

- name: create bastion Environment
  cloudformation:
#    profile: "{{ eksexample_aws_profilename }}"
    stack_name: "{{ eksexample_clustername }}-bastion"
    state: "present"
    region: "{{ eksexample_region }}"
    disable_rollback: false
    template_parameters:
      EKSBastionInstanceType: "{{ eksexample_bastion_instancetype }}"
      EKSBastionKeyPairName: "ec2-key"
    template: "./cloudformation/eks-bastion.template.yaml"
  register: bastion_informations

- name: save outputs to local file for ref 
  copy: 
    content: "{{ bastion_informations.stack_outputs | to_nice_yaml }}" 
    dest: ./vars/dynamic/eksexample_bastion.yaml